<?php

namespace Louvre\BilletBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{
    public function getReservationsByDate(\DateTime $date)
    {
        $query = $this->createQueryBuilder('r')
            ->where('r.datevisite = :date')
            ->setParameter('date', $date)
            ->getQuery()
        ;

        return $query->getResult();
    }
}
